
//User Tests

###
POST http://localhost:8080/authenticate/createUser
Content-Type: application/json

{
    "userId": "testuser",
    "email": "testuser@gmail.com",
    "password": "pass"
}

###
POST http://localhost:8080/authenticate/login
Content-Type: application/json

{
    "userId": "testuser",
    "password": "pass"
}

###
POST http://localhost:8080/authenticate/login
Content-Type: application/json

{
}

###
PATCH http://localhost:8080/user/testuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGF0aSIsImlhdCI6MTYyMTYwNjY1MCwiZXhwIjoxNjIzMjI4NTU3Mjg3fQ.4HtjcsQ3Ifd2hof2gQPdTRejXUkdsYQDU6BeTCuADsk
Content-Type: application/json

{
    "steampath": "test",
    "originpath": "testorigin"
}

###
DELETE  http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGF0aSIsImlhdCI6MTYyMTYwNjY1MCwiZXhwIjoxNjIzMjI4NTU3Mjg3fQ.4HtjcsQ3Ifd2hof2gQPdTRejXUkdsYQDU6BeTCuADsk
Content-Type: application/json

{
    "_id": "60c0b405db58f3394854b0b8"
}

###
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGF0aSIsImlhdCI6MTYyMTYwNjY1MCwiZXhwIjoxNjIzMjI4NTU3Mjg3fQ.4HtjcsQ3Ifd2hof2gQPdTRejXUkdsYQDU6BeTCuADsk

###
GET http://localhost:3000/user/find
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGF0aSIsImlhdCI6MTYyMTYwNjY1MCwiZXhwIjoxNjIzMjI4NTU3Mjg3fQ.4HtjcsQ3Ifd2hof2gQPdTRejXUkdsYQDU6BeTCuADsk

{
    "userId": "Timur"
}